# Site settings
title: CHAI's blog
author: CHAI
description: Good Good Study
url: https://chaideblog.github.io/

# Building settings
mardown: redcarpet
permalink: /:title/
highlighter: rouge
paginate: 20
paginate_path: "page:num"
encoding: UTF-8
future: true




# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
